[book]
authors = ["CASE", "Cristóbal Allendes"]
language = "en"
multilingual = false
src = "."
title = "Genus"

[build]
build-dir = "../book"
use-default-preprocessors = true

[output.html]
mathjax-support = true
